"""Initial migration: create all tables

Revision ID: d9c9cdcccd40
Revises: 
Create Date: 2025-06-17 14:38:36.619466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c9cdcccd40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False, comment='API 키 이름'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='API 키 값'),
            sa.Column('service_name', sa.String(length=50), nullable=False, comment='서비스명 (service_a, service_b, service_c)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('allowed_ips', sa.Text(), nullable=True, comment='허용된 IP 주소 목록 (JSON 배열)'),
    sa.Column('description', sa.Text(), nullable=True, comment='API 키 설명'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False, comment='템플릿 이름'),
    sa.Column('template_type', sa.Enum('EMAIL', 'SMS', 'KAKAO', name='templatetype'), nullable=False, comment='템플릿 타입'),
    sa.Column('subject', sa.String(length=500), nullable=True, comment='제목 (이메일용)'),
    sa.Column('body_text', sa.Text(), nullable=True, comment='텍스트 본문'),
    sa.Column('body_html', sa.Text(), nullable=True, comment='HTML 본문 (이메일용)'),
    sa.Column('variables', sa.Text(), nullable=True, comment='템플릿 변수 목록 (JSON)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('description', sa.Text(), nullable=True, comment='템플릿 설명'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='템플릿 카테고리'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False, comment='사용된 API 키 ID'),
    sa.Column('request_id', sa.String(length=100), nullable=False, comment='요청 고유 ID'),
    sa.Column('sender_email', sa.String(length=255), nullable=False, comment='발송자 이메일'),
    sa.Column('sender_name', sa.String(length=100), nullable=True, comment='발송자 이름'),
    sa.Column('recipient_email', sa.String(length=255), nullable=False, comment='수신자 이메일'),
    sa.Column('recipient_name', sa.String(length=100), nullable=True, comment='수신자 이름'),
    sa.Column('subject', sa.String(length=500), nullable=False, comment='이메일 제목'),
    sa.Column('body_text', sa.Text(), nullable=True, comment='텍스트 본문'),
    sa.Column('body_html', sa.Text(), nullable=True, comment='HTML 본문'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='발송 상태 (pending, sent, failed)'),
    sa.Column('ncloud_request_id', sa.String(length=100), nullable=True, comment='NCloud 요청 ID'),
    sa.Column('ncloud_response', sa.Text(), nullable=True, comment='NCloud 응답 데이터 (JSON)'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='예약 발송 시간'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='실제 발송 시간'),
    sa.Column('has_attachments', sa.Boolean(), nullable=True, comment='첨부파일 여부'),
    sa.Column('attachment_info', sa.Text(), nullable=True, comment='첨부파일 정보 (JSON)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='재시도 횟수'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False, comment='사용된 API 키 ID'),
    sa.Column('schedule_name', sa.String(length=100), nullable=False, comment='스케줄 이름'),
    sa.Column('schedule_type', sa.Enum('EMAIL', 'SMS', 'KAKAO', name='scheduletype'), nullable=False, comment='스케줄 타입'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False, comment='예약 실행 시간'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='시간대'),
    sa.Column('payload', sa.Text(), nullable=False, comment='발송 데이터 (JSON)'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='schedulestatus'), nullable=True, comment='스케줄 상태'),
    sa.Column('executed_at', sa.DateTime(), nullable=True, comment='실제 실행 시간'),
    sa.Column('max_retry', sa.Integer(), nullable=True, comment='최대 재시도 횟수'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='현재 재시도 횟수'),
    sa.Column('retry_interval', sa.Integer(), nullable=True, comment='재시도 간격 (초)'),
    sa.Column('result', sa.Text(), nullable=True, comment='실행 결과 (JSON)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False, comment='사용된 API 키 ID'),
    sa.Column('request_id', sa.String(length=100), nullable=False, comment='요청 고유 ID'),
    sa.Column('sender_phone', sa.String(length=20), nullable=False, comment='발송자 전화번호'),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False, comment='수신자 전화번호'),
    sa.Column('message', sa.Text(), nullable=False, comment='SMS 메시지 내용'),
    sa.Column('message_type', sa.String(length=10), nullable=False, comment='메시지 타입 (SMS, LMS, MMS)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='발송 상태 (pending, sent, failed)'),
    sa.Column('ncloud_request_id', sa.String(length=100), nullable=True, comment='NCloud 요청 ID'),
    sa.Column('ncloud_response', sa.Text(), nullable=True, comment='NCloud 응답 데이터 (JSON)'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='예약 발송 시간'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='실제 발송 시간'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='재시도 횟수'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_sms_logs_id'), 'sms_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_logs_id'), table_name='sms_logs')
    op.drop_table('sms_logs')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
